name: GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: master

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - name: Set CI mode
              run: npm ci

            - name: Build BlockBook
              run: npm install && npm run build -- --output-public-path=/gutenberg-blockbook-styleguide && cp dist/index.html dist/404.html

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
